import {z} from 'zod';
import {owner,db,fail,originCheck} from '@/lib/server';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(x=>!isNaN(Date.parse(x))&&new Date(x).toISOString().slice(0,10)===x,'Invalid date');
const run=z.object({name:z.string().min(1).max(120),date,distance:z.number().positive().max(500),seconds:z.number().positive().max(604800),hr:z.number().min(25).max(240).nullish(),cadence:z.number().min(20).max(300).nullish(),elevation:z.number().min(0).max(30000).nullish(),rpe:z.number().min(1).max(10).nullish(),source:z.enum(['manual','screenshot','gpx','tcx','intervals','strava-link']),url:z.string().max(600).optional().refine(x=>!x||/^https:\/\/(www\.)?(strava\.com|strava\.app\.link)\//.test(x),'Use a Strava HTTPS link'),splits:z.array(z.number().positive().max(7200)).max(500).optional(),notes:z.string().max(5000).optional(),files:z.array(z.string().uuid()).max(6).optional(),timeBasis:z.enum(['moving','elapsed']).optional()});
const checkin=z.object({date,sleep:z.number().min(0).max(24).nullable(),fatigue:z.number().int().min(1).max(5),soreness:z.number().int().min(1).max(5),restingHR:z.number().min(25).max(180).nullable(),notes:z.string().max(2000)});
const goal=z.object({name:z.string().min(1).max(100),date,distance:z.number().min(1).max(200),targetSeconds:z.number().positive().max(172800)});
export async function GET(){try{const uid=await owner();const rows=await db().prepare('SELECT id,kind,body FROM records WHERE owner=? ORDER BY created DESC LIMIT 2000').bind(uid).all();return Response.json({records:rows.results.map((r:any)=>({id:r.id,kind:r.kind,...JSON.parse(r.body)}))},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(req:Request){try{originCheck(req);const uid=await owner();if(Number(req.headers.get('content-length'))>30000)throw new Error('INPUT:Request too large.');const input:any=await req.json();const schema=input.kind==='run'?run:input.kind==='checkin'?checkin:input.kind==='goal'?goal:null;if(!schema)throw new Error('INPUT:Unknown record type.');const parsed=schema.safeParse(input.body);if(!parsed.success)throw new Error('INPUT:'+parsed.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; '));const body:any=parsed.data;if(body.files?.length){for(const f of body.files){if(!await db().prepare('SELECT id FROM files WHERE id=? AND owner=?').bind(f,uid).first())throw new Error('INPUT:Attachment not found.')}}
const id=input.kind==='run'?crypto.randomUUID():`${uid}:${input.kind}:${input.kind==='goal'?'primary':body.date}`;
await db().prepare('INSERT INTO records (id,owner,kind,body,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body,created=excluded.created WHERE records.owner=excluded.owner').bind(id,uid,input.kind,JSON.stringify(body),new Date().toISOString()).run();return Response.json({id,...body,kind:input.kind});}catch(e){return fail(e)}}
export async function DELETE(req:Request){try{originCheck(req);const uid=await owner();const {id}=await req.json() as {id:string};await db().prepare('DELETE FROM records WHERE id=? AND owner=?').bind(String(id),uid).run();return Response.json({ok:true})}catch(e){return fail(e)}}
